using UnityEngine;

public class TriggerReposer : MonoBehaviour
{
    public EquiperCasqueVR casque; // R√©f√©rence au casque
    public static int nbFois=0;

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Casque"))
        {
            // V√©rifier si le casque est d√©j√† √©quip√© avant de proc√©der
            if (casque.AEteEquipe)
            {
                Debug.Log("‚ö†Ô∏è Le casque est d√©j√† √©quip√© !");
                return; // Ne pas continuer si le casque est d√©j√† √©quip√©
            }

            // R√©initialiser la position du casque √† son socle
            Transform socleCasque = casque.socleCasque;
            if (socleCasque != null &&nbFois%2==0)
            {
                nbFois++;
                Debug.Log("üîÑ Tentative de repositionnement du casque...");
                other.transform.SetParent(null); // D√©tacher le casque de son parent actuel
                other.transform.position = socleCasque.position; // Positionner le casque sur le socle
                other.transform.rotation = socleCasque.rotation; // Rotation du casque sur le socle
                Debug.Log("üìå Casque repositionn√© sur le socle !");
            }else
            {
                Debug.LogError("‚ö†Ô∏è Socle du casque non trouv√© !");
            }
        }
    }
}
