using UnityEngine;

public class TriggerFuite2 : MonoBehaviour
{   
    public AudioSource steamSound; // R√©f√©rence √† la source audio de la fuite de vapeur
    public bool isTriggered = false;
    public GameObject PressurisedSteam;
    public GameObject Tape1;
    public GameObject groundFog1;
    public GameObject groundFog2;
    public AudioSource VoixTrigger;
    public RedButton2 redButton; // R√©f√©rence au script RedButton

    void Start()
    {
        Tape1.SetActive(false); // Assurez-vous que le GameObject "tape" est d√©sactiv√© au d√©part
        PressurisedSteam.SetActive(true); // Assurez-vous que la fuite de vapeur est activ√©e au d√©part
    }

    private void OnTriggerEnter(Collider other)
    {
        if (redButton != null && !redButton.isPressed)
        {
            VoixTrigger.Play();
            Debug.Log("üîä Voix d√©clench√©e !");
            return;
        }
        if (other.CompareTag("tape"))
        {
            groundFog1.SetActive(false); // D√©sactiver le brouillard au sol 1
            groundFog2.SetActive(false); // D√©sactiver le brouillard au sol 2
            Tape1.SetActive(true); // D√©sactiver le GameObject "tape"
            steamSound.Stop(); // Arr√™ter le son de la fuite de vapeur
            PressurisedSteam.SetActive(false); // D√©sactiver la fuite de vapeur
            isTriggered = true; // Marquer le d√©clencheur comme activ√©
            Debug.Log("Escape sequence triggered!");
        }
    }
}
